version = 0.1
[default.deploy.parameters]
stack_name = "podcast-summarization"
resolve_s3 = true
s3_prefix = "podcast-summarization"
region = "us-west-2"
profile = "bubai-bal"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
